## Import Relevant packages

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
sns.set()

from sklearn.linear_model import LinearRegression 

## Loading the Dataset 

In [2]:
data= pd.read_csv("1.02.+Multiple+linear+regression.csv")
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

#### Only Difference from the Previous simple linear Regression is "Addition of an extra column Rand 1,2,3".This column is Assigned with random vales among 1,2,3


# Multiple Linear Regression

### Declaring the Variables

In [3]:
x= data[['SAT',"Rand 1,2,3"]]   # Independent variable
y=data["GPA"]                   # Dependent variable

### Regression 

In [4]:
# Create An Instance of LInearRegression class
reg= LinearRegression()
reg.fit(x,y)

LinearRegression()

### Obtaining parameters

In [5]:
# coefficients 

reg.coef_

array([ 0.00165354, -0.00826982])

In [6]:
# intercept 

reg.intercept_

0.29603261264909264

In [7]:
x.shape

(84, 2)

In [8]:
# R-Squared

reg.score(x,y)

0.40668119528142843

In [9]:
# Calculating Adjusted R-Square from formula

r_square= reg.score(x,y)

#from above shape of x,we can see that "no.of observations =84","no.of Predictors = 2"

n=x.shape[0]
p=x.shape[1]

adjusted_rsquare= 1-(1-r_square)*((n-1)/(n-p-1))
print(adjusted_rsquare)

0.39203134825134023


We can see that Adjusted R-square is considerably less than R-square. So,There is Insignificant Feature to GPA .It can be Determined 
By Feature Selection

## Feature Selection 

In [10]:
from sklearn.feature_selection import f_regression

f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [11]:
# index 0 -> F statistics 
# index 1 -> P-Values 

# Considering P-values
f_regression(x,y)[1]

array([7.19951844e-11, 6.76291372e-01])

So,we can see that 'Rand 1,2,3' p-value is Too high and Symbolizes that it is "Insignficant in Determining the GPA"